### PR TITLE
#287 - Material Design 3

### PR DESCRIPTION
**Pull request by SapuSeven**
_Want to try out the upcoming version? Request access here: https://forms.gle/x9VNNAVwrwbnMPsX6_

With this update I will completely rewrite most of the UI code with the goal to modernize the app structure to be up-to-date with most current standards and guidelines.
It's a long and gradual process and I'm only working on it in my spare time, so I will track my progress here:

### Migrated Activities

- [x] Login
- [x] QR Code Scan
- [x] Login Data Input
- [x] Widget Configuration
- [x] Shortcut Configuration
- [x] Info Center
- [x] Free Rooms
- [x] Settings
- [x] Main
- [x] Widget

### TODO

- [x] Test QR Code scanning
- [x] Test all features with actual data
- [ ] <strike>Implement yearly profile updates (Data update on school year change)</strike> Not a fan of this one - There should be a better way to update data on demand
- [x] Implement profile management (Deleting/Editing profiles)
- [x] Implement info center message and homework attachments
- [ ] <strike>Implement</strike> Test absence checking (implemented but not tested with real data - missing Untis teacher account)
- [x] Implement lesson topic editing
- [x] Implement new DataStore preferences - right now, preferences don't work
- [x] Implement bookmarks
- [x] Implement holidays
- [x] Implement Untis Messenger integration
- [x] Implement date picker for timetable
- [x] Implement persistent timetable zoom
- [ ] Implement extensive error logging using Sentry
- [x] Implement auto-mute
- [x] Implement break notifications
- [x] Implement composable widgets
- [ ] Fix widget issues on older Android versions
- [ ] Remove old layouts
- [ ] Refactor composable activities to split state from ui
- [ ] #344 

### Notes
- The new UI code could probably be refactored to further decouple UI components - This may be addressed later if I have time.
- Adaptive Launcher Icon support has been implemented for Android 13+
- Adaptive Shortcut Icons don't work yet
- The WeekView will still uses the old custom view implementation as updating it would cause more trouble than it's worth
- The timetable database interface isn't written with coroutines in mind, so element picker performance is poor
- Widgets don't yet work on older Android versions and have some usability issues (no proper error handling, no message on free days, unnecessary element picker for daily message widget). Also, a homework/event widget would be nice.

### CODE REVIEW

**Comment by SapuSeven** [comment]
https://stackoverflow.com/questions/73420996/androidx-datastore-multiple-profiles

I'd appreciate any help on this issue

**Comment by lm41** [comment]
I'm guessing that you have tried that:
```kotlin
val Context.dataStore: DataStore<Preferences> by preferencesDataStore(name = "$preferences_id")
```
But I don't know if this would work.

**Comment by SapuSeven** [comment]
Yes, that's the idea, but I don't have access to `$preferences_id` at file-level.
I'm not sure if this is even possible. `by preferencesDataStore` is some kind of read-only property, so I can't change it. Maybe using DataStore instances is the wrong approach.

**Comment by lm41** [comment]
As I'm still in school i could test some items on the todo checklist. Just tell me what is ready to test :D

**Comment by lm41** [comment]
QR Code Scanning:
It works half way. The qr code was read the right way and the fields were filled right, but still detected empty

**Comment by SapuSeven** [comment]
@lm41 the qr code should be an encoded URL. Could you scan the code with another app and tell me the URL please (without the secret key ofc)?

**Comment by lm41** [comment]
untis://setschool?url=ajax.webuntis.com&school=xx&user=xx&key=xx&schoolNumber=xx

**Comment by lm41** [comment]
@SapuSeven Can you create a DM on [matrix](https://matrix.to/#/@lm41:tchncs.de), so I can send you a video of the issue?

**Comment by SapuSeven** [comment]
(Example QR Code for Testing)

**Comment by lm41** [comment]
This is a possible fix for the "This Field cannot be empty!" error message after a qr scan.
I have simply moved the error initialization after the URI parsing
```diff
diff --git a/app/src/main/java/com/sapuseven/untis/activities/LoginDataInputActivity.kt b/app/src/main/java/com/sapuseven/untis/activities/LoginDataInputActivity.kt
index ee3ff00..a616028 100755
--- a/app/src/main/java/com/sapuseven/untis/activities/LoginDataInputActivity.kt
+++ b/app/src/main/java/com/sapuseven/untis/activities/LoginDataInputActivity.kt
@@ -121,9 +121,6 @@ class LoginDataInputActivity : BaseComposeActivity() {
 				val apiUrl = rememberSaveable { mutableStateOf(existingUser?.apiUrl) }
 				val skipAppSecret = rememberSaveable { mutableStateOf<Boolean?>(null) }
 
-				val schoolIdError = schoolId.value.isNullOrEmpty()
-				val usernameError = anonymous.value != true && username.value.isNullOrEmpty()
-				val passwordError = anonymous.value != true && password.value.isNullOrEmpty()
 				val proxyUrlError =
 					!proxyUrl.value.isNullOrEmpty() && !Patterns.WEB_URL.matcher(proxyUrl.value!!)
 						.matches()
@@ -131,9 +128,6 @@ class LoginDataInputActivity : BaseComposeActivity() {
 					!apiUrl.value.isNullOrEmpty() && !Patterns.WEB_URL.matcher(apiUrl.value!!)
 						.matches()
 
-				val anyError =
-					schoolIdError || usernameError || passwordError || proxyUrlError || apiUrlError
-
 				var advanced by rememberSaveable {
 					mutableStateOf(
 						proxyUrl.value?.isNotEmpty() == true ||
@@ -159,6 +153,13 @@ class LoginDataInputActivity : BaseComposeActivity() {
 					}
 				}
 
+				val schoolIdError = schoolId.value.isNullOrEmpty()
+				val usernameError = anonymous.value != true && username.value.isNullOrEmpty()
+				val passwordError = anonymous.value != true && password.value.isNullOrEmpty()
+
+				val anyError =
+					schoolIdError || usernameError || passwordError || proxyUrlError || apiUrlError
+
 				fun loadData() {
 					coroutineScope.launch {
 						LoginHelper(
```

**Comment by lm41** [comment]
The QR-Code Scanning is tested for the codes with this scheme  
`appLinkData.scheme == "untis" && appLinkData.host == "setschool"`. 
I don't have a qr code with `UntisSchoolInfo`. This still needs to be tested.

**Comment by lm41** [comment]
if the selected profile is deleted, no new one is selected and you get an "Invalid profile ID" error when opening the infocenter.

**Comment by SapuSeven** [comment]
> if the selected profile is deleted, no new one is selected and you get an "Invalid profile ID" error when opening the infocenter.

I will address this when I implement the new preferences and replace `PreferenceHelper`.

**Comment by lm41** [comment]
https://user-images.githubusercontent.com/59062169/190012170-176c8613-a81a-4fc4-bb51-f8c578d70f6d.mp4

Some weird timetable display issue, where one week is displayed with another week and the original week is empty. Restarting the app fixes the problem. This occured two times in my testing phase (the last 5-6 days)

**Comment by SapuSeven** [comment]
Thanks, should be fixed with 6cd538a55848e6138a4da9f1cf2f84f3b5fe33d3.

**Comment by Lauritz-Tieste** [comment]
When is the Material Design 3 update expected to be ready?

**Comment by SapuSeven** [comment]
Not sure yet. Most features have already been migrated (see the checklist in the first post) but I would expect everything to be done by the end of the year.

**Comment by lm41** [comment]
`[] Implement extensive error logging using Sonar` will you use sonar, or sentry like mentioned in #253

**Comment by SapuSeven** [comment]
Damn, you're right, I confused the two 🤦‍♂️
Of course I meant Sentry

**Comment by MatsG23** [comment]
Could you release a pre-release version of the app so that Material 3 and other changes can be tested out?
Or is the app not runnable at the current state?

Also, will it be possible to opt-out of Sentry?

**Comment by SapuSeven** [comment]
Good idea, I will look into creating an alpha channel to test it publicly.
Sentry isn't fully implemented yet, but I assume there will be a possibility to opt out (maybe only for additional data collection - crashes should always be reported imo).

**Comment by SapuSeven** [comment]
@MatsG23 I set up a form if you want to request access to closed testing: https://forms.gle/x9VNNAVwrwbnMPsX6

**Comment by MatsG23** [comment]
Thanks. I believe a testing version of the app is still in the verification process of Google Play.
General thing: Would it be possible to also release alphas and betas on GitHub (marked as pre-release)? By using the GitHub Releases way you would not need a Google account to setup the testing.

**Comment by SapuSeven** [comment]
The closed testing is only intended for this update, so I probably won't add an alternative method to get releases.
When a new version is ready to be released, a GitHub Pre-Release gets created automatically, as well as an update for Play Store Beta users. If you want to download "nightly" builds (i.e. the current state of `develop`), they're available [on my website](https://sapuseven.com/app/BetterUntis/).

I'm also currently having some troubles with Play Store rejecting the material-3 update, so it might take another day or two until it shows up.

**Comment by SapuSeven** [comment]
Google Play update should be live. Currently, there may be an issue where the app crashes immediately, but this should be resolved by clearing the app data. I'll implement a fix for that later.

**Comment by lm41** [comment]
I have room access and can select them in the free rooms feature. If I select a room there i can also see the timetables. 
BUT I cannot select them via the rooms dialogue or the Add Timetable dialogue. They are all greyed out. Is there something I am missing?

**Comment by lm41** [comment]
Ok, nevermind. I've uninstalled the app and now it works. Maybe we have to implement something that checks if timetable permissions were updated as it was in my case.

**Comment by lm41** [comment]
```diff
Do not apply
```
This fixes the problem of not showing the Lesson details correctly if you have a custom days to display set in the settings. I wasn't exactly shure what offset did, but removing it fixes the problem in the most cases. There is only an issue if you have snap to days disabled and it remembers the days to display. So it actually snaps to days but only to the value of the out-greyed "Days to display". So this is an other bug in the code, not related to the removal of the offset.

**Comment by lm41** [comment]
I've messed up. The fix above isn't working today anymore :/ I think I have to live with the problem or dig deeper to the origin of it. @SapuSeven

**Comment by SapuSeven** [comment]
Alright, most features should be fully functional by now.
I decided to promote the update to beta and merged into `develop` to get more feedback from beta testing on Google Play.
The TODOs of this PR still need to be completed before the final release though.

**Comment by lm41** [comment]
@SapuSeven The auto-mute feature isn't working properly with my fix. It now mutes on saturdays... The offset has to be readded again.

**Pull request merged**
