### PR TITLE
Update german translation

### PR DESCRIPTION
**Pull request by nautilusx**
Thank you for your great app!

I did an update for the german translation.

But some strings are missing like "Auto-Mute" and the options for the "Use colors provided from your school".

weblate.org would be great ;o)

### CODE REVIEW

**Comment by SapuSeven** [comment]
First of all, good translations, I'll gladly merge them.
But could you change the base branch to `develop` instead of `master`? I want to keep all development commits in there and only merge to master for each release.

Secondly, about Weblate: My current web server doesn't have sufficient resources, so I applied for a free hosting on their servers. I'll keep you updated at #27.

**Comment by SapuSeven** [comment]
Oh, and I'll work on the missing strings tomorrow

**Comment by nautilusx** [comment]
I hope it works

**Comment by SapuSeven** [comment]
Perfect, thanks!

**Comment by nautilusx** [comment]
We did it live now with weblate.org on FOSDEM! ;o)

https://live.fosdem.org/watch/aw1120
https://fosdem.org/2020/schedule/event/clc_weblate_localize_your_project_the_developer_way/

**Comment by SapuSeven** [comment]
That's awesome!
Can I rewatch the stream somewhere? I missed the beginning...

**Comment by nautilusx** [comment]
Hopefully here: https://video.fosdem.org/2020/AW1.120/

I have fixed a few small bugs live. ;o)

**Pull request merged**
