### PR TITLE
Improve About Screen

### PR DESCRIPTION
**Pull request by Domi04151309**
This pull request improves the about screen by adding information about contributors and used libraries.

### CODE REVIEW

**Comment by Perflyst** [comment]
It does not really make sense to list all contributors. Only core contributors should be listed.

**Comment by Domi04151309** [comment]
Well how do you differentiate between core contributors and non core contributors?

**Comment by Perflyst** [comment]
If every typo fix by some random user gets added to this list, it will be very bloated.

**Comment by Domi04151309** [comment]
I took the entries of the contributors list of this GitHub repository for reference. It's probably not the best because I'm sure you also contributed a lot although you don't show up there.

**Comment by Perflyst** [comment]
I dont care if I am mentioned in this list, I just dont want that a lot of random people are listed there - because then it makes no sense. If you want to list the contributors, maybe mention SapuSeven and make another PreferenceCategory with a link to the contributors page on github

**Comment by Domi04151309** [comment]
It probably makes sense to show the big community behind the app but you're right regarding the fact that SapuSeven should have a special position. Why don't we ask him about his point of view.

**Comment by SapuSeven** [comment]
That's a really tricky question.

It's hard to determine "core contributors", so a link to the GitHub contributors page would probably be easiest. However it'd be cool to show major contributions (like new features) directly from within the app.
As of now, there aren't that many contributors, but this will probably change in the future.

Additionally, there are some users who helped by opening bug reports and other issues, which would not be shown in any list.

So all in all, the best solution in my opinion is to provide a link to the GitHub contributors page or even better: a wiki page to list all changes from contributors. That way, even relatively small contributions can be credited.

**Comment by Domi04151309** [comment]
I think for now it shouldn't be that big of a deal because as SapuSeven wrote, it aren't that many people. Nonetheless I'll think about a nice looking alternative.

**Review by SapuSeven — CHANGES_REQUESTED** [review]
Careful. A slow internet connection may lead to an ANR when fetching the contributors list.
This really has to be asynchronous.

But I think its a pretty good idea to fetch contributors from GitHub dynamically.

**Comment by Domi04151309** [comment]
I have already thought about that but didn't quite know how to make it asynchronous. Do I have to create a new thread for this?

**Comment by SapuSeven** [comment]
Basically yes. This app uses Kotlin Coroutines for asynchronous tasks.
Take a look at `com.sapuseven.untis.activities.InfoCenterActivity` (`refreshMessages()` and `loadMessages()`):
The simplest way is to use `GlobalScope.launch(Dispatchers.Main) {}` and execute suspending functions within that code block. It took me a while to get it, I hope you can figure it out.

**Comment by Domi04151309** [comment]
I'm not sure if this is implemented correctly, but it should be asynchronous now.

**Comment by SapuSeven** [comment]
Almost ;)
I'll merge now and work on it a little more

**Pull request merged**
