### PR TITLE
Update screenshots

### PR DESCRIPTION
**Pull request by Domi04151309**
I have created some new screenshots because the current ones are pretty old.

### CODE REVIEW

**Comment by SapuSeven** [comment]
Looks great!

Could you add some dummy absences for the last screenshot?

**Review by SapuSeven — CHANGES_REQUESTED** [review]
Looks great!

Could you add some dummy absences for the last screenshot?

**Review by SapuSeven — DISMISSED** [review]
Perfect, thanks!

**Comment by Domi04151309** [comment]
Don't forget to update the screenshots on the play store.

**Pull request merged**
