### PR TITLE
Add Widgets and Shortcuts

### LINKED ISSUE #88: [Feature Request] Widgets and Shortcuts
**Describe the solution you'd like**

There kind of is some unused code already in the app and a widget would be nice.

- [x] Timetable
- [x] Daily Messages
- [x] Timetable Link

### PR DESCRIPTION
**Pull request by Domi04151309**
Closes #88

### CODE REVIEW

**Comment by SapuSeven** [comment]
I will take a look at this at the weekend. Thank you for your work and effort so far, I don't expect any major problems.

**Comment by SapuSeven** [comment]
Quick status update:
I still need to thoroughly test this myself, but as I'm technically not a student any more I don't have easy access to proper timetable data.
Because of that, I'm working on recreating the Untis API on the server side so that I can easily use fake data for testing. This and the fact that my server is currently experiencing network problems may delay this PR a little further.

**Comment by Domi04151309** [comment]
Sadly I cannot provide you with an account anymore because my school disabled the class accounts a week ago.

**Comment by SapuSeven** [comment]
Some improvement ideas:

- [x] Widget Configuration: the "please select a profile" text should take up less space (can maybe even be removed completely)
- [x] The widgets should have a smaller minimum size
- [x] The header section of the widgets should be more compact
- [ ] The timetable widget layout should have an improved layout for better readability

The Timetable Shortcut works well.

Feel free to discuss any of these if you have other thoughts about it.

**Comment by Domi04151309** [comment]
I have tried to create similar widgets to the original app's which is where the minimum size comes from. A smaller size may conflict with long names. A toggle for a compact header would be a nice idea so people who like a more compact look can achieve it. You're right the layout is not the best and doesn't allow scrolling which is why it might be a good idea to use a ListView instead which would require some extra work.

About the configuration screen: I have tried to implement a different approach that moves the text into the action bar. What are your thoughts about that solution?

**Comment by SapuSeven** [comment]
Your idea for the configuration screen could work well.

I didn't even notice the lack of scrolling when testing... though I think that would be a necessity for a useful widget, to be honest.

**Comment by SapuSeven** [comment]
Also, I have added credentials for a demo account [to the Wiki](https://github.com/SapuSeven/BetterUntis/wiki/Testing-API#official-demo-accounts) which could be useful for testing.

**Comment by SapuSeven** [comment]
Still TODO for the new timetable widget:
- [x] Sort list items by time
- [ ] Show loading indicator
- [x] Show indicator if there are no lessons today
- [x] Reliably update the timetable data 
- [x] Only show rooms and teachers that are not empty and consider substitutions
- [x] ~~Implement~~ Fix "Tap to retry" ~~on error~~ showing empty widget after reloading

**Comment by Domi04151309** [comment]
I think it already updates every hour with the current widget configuration.

**Comment by SapuSeven** [comment]
In that case I have to do some debugging, as I noticed the widget on my
installation still shows yesterday's timetable.

**Comment by SapuSeven** [comment]
I did some digging and found the reason for the lack of updating.
Yes, the widget updates every hour, but the `RemoteViewsFactory` doesn't reload the items, because it's being reused by Android and list data updates happen only in the constructor.

I'll push a fixed version shortly once it's confirmed I solved the issue.

**Comment by SapuSeven** [comment]
Oh, and one more minor thing:
Please universally use tabs for indentation (especially the `strings.xml` from this branch contains quite a lot of mixed indentation styles).

The entire project uses tabs and I'd like to keep it consistent.

**Comment by Domi04151309** [comment]
Sure, that's just something Android Studio messed up a bit when adding auto-generated resources. I realized it too late but I'll pay more attention to it in the future.

**Review by SapuSeven — APPROVED** [review]

**Comment by SapuSeven** [comment]
I created a new branch for this PR as I intend to merge this soon and include widgets in the next release, but also want keep the possibility to continue working on these features separately from the main branch (for example to add your dual line action bar). You can then submit PRs to this new branch.

**Comment by Domi04151309** [comment]
Actually I am not a big fan of the dual-line action bar because it looks too crowded.

**Pull request merged**
