### PR TITLE
Gray Out Disallowed

### LINKED ISSUE #84: [Feature Request] Gray out timetables you don't have permissions for
**Describe the solution you'd like**

Gray out the items in `ElementPickerDialog `when `displayAllowed` is false.

### PR DESCRIPTION
**Pull request by Domi04151309**
Closes #84 

Additionally, it will move the items that are accessible to the front.
I couldn't really perform a lot of testing because I am only allowed to access my personal and my class's timetable.

### CODE REVIEW

**Comment by Domi04151309** [comment]
What's the status of this pr?

**Comment by SapuSeven** [comment]
I still want to test this before merging.
Ready either this or next weekend.

**Comment by SapuSeven** [comment]
Is it intended that disabled items are still clickable?

**Comment by Domi04151309** [comment]
Yes that's intended in case of a faulty categorization.

**Review by SapuSeven — APPROVED** [review]
Alright, looks good to me.

**Pull request merged**
