### PR TITLE
Switch to kotlin gradle dsl and gradle version catalog

### PR DESCRIPTION
**Pull request by lm41**
This PR migrates the build scripts from groovy to the gradle kotlin dsl and introduces the version catalog feature from gradle.

It is now (at least for me) easier to add libraries and it is more welcoming for outsiders if you use modern language features. So you can use the Kotlin knowledge you already have to improve the build-scripts as well without having to learn groovy first.

Please let me know what you think of this change.

### CODE REVIEW

**Comment by SapuSeven** [comment]
I really welcome this change, never had the time to do it myself.
However, please keep in mind that future development happens on the `api` branch, which includes a lot of changes including a separate module for API-related code and a complete architecture rewrite.
There are no more 4.x-releases planned (besides #455) as it will be difficult to merge big changes to the new version.
I suggest to wait or contribute directly to `api`.

**Comment by lm41** [comment]
Hey :D
Thank you for your quick reply.
If it's ok with you, I would choose to base these changes on the api branch and contribute directly there.

**Comment by lm41** [comment]
Hey again.

I've now completed the change with the `api` branch as the base.
> [!WARNING]
>  It fully compiles BUT I get a `RuntimeException` if I try do run the debug artifact.

<details><summary>Error Information</summary>
<p>

```
type: crash
osVersion: google/cheetah/cheetah:15/AP4A.241205.013/2024121200:user/release-keys
flags: dev options enabled
package: com.sapuseven.untis.debug:28916652, targetSdk 33
process: com.sapuseven.untis.debug
processUptime: 458 + 80 ms

java.lang.RuntimeException: Unable to instantiate application com.sapuseven.untis.activities.App package com.sapuseven.untis.debug: java.lang.ClassNotFoundException: Didn't find class "com.sapuseven.untis.activities.App" on path: DexPathList[[zip file "/data/app/~~yRpLZk00pFOSXXnDhFZMjw==/com.sapuseven.untis.debug-ZgXMJHkrV6aXXVdQoOZRhA==/base.apk"],nativeLibraryDirectories=[/data/app/~~yRpLZk00pFOSXXnDhFZMjw==/com.sapuseven.untis.debug-ZgXMJHkrV6aXXVdQoOZRhA==/lib/arm64, /data/app/~~yRpLZk00pFOSXXnDhFZMjw==/com.sapuseven.untis.debug-ZgXMJHkrV6aXXVdQoOZRhA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1480)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1405)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7585)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2458)
	at android.os.Handler.dispatchMessage(Handler.java:109)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:887)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sapuseven.untis.activities.App" on path: DexPathList[[zip file "/data/app/~~yRpLZk00pFOSXXnDhFZMjw==/com.sapuseven.untis.debug-ZgXMJHkrV6aXXVdQoOZRhA==/base.apk"],nativeLibraryDirectories=[/data/app/~~yRpLZk00pFOSXXnDhFZMjw==/com.sapuseven.untis.debug-ZgXMJHkrV6aXXVdQoOZRhA==/lib/arm64, /data/app/~~yRpLZk00pFOSXXnDhFZMjw==/com.sapuseven.untis.debug-ZgXMJHkrV6aXXVdQoOZRhA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
	at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:51)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1363)
	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1473)
	... 11 more
	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/sapuseven/untis/activities/Hilt_App;
		at java.lang.VMClassLoader.findLoadedClass(Native Method)
		at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:1276)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:621)
		... 16 more
	Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sapuseven.untis.activities.Hilt_App" on path: DexPathList[[zip file "/data/app/~~yRpLZk00pFOSXXnDhFZMjw==/com.sapuseven.untis.debug-ZgXMJHkrV6aXXVdQoOZRhA==/base.apk"],nativeLibraryDirectories=[/data/app/~~yRpLZk00pFOSXXnDhFZMjw==/com.sapuseven.untis.debug-ZgXMJHkrV6aXXVdQoOZRhA==/lib/arm64, /data/app/~~yRpLZk00pFOSXXnDhFZMjw==/com.sapuseven.untis.debug-ZgXMJHkrV6aXXVdQoOZRhA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
		... 19 more
```


</p>
</details> 

I am unsure if this is just the case or if I have created the problem because the current `api` branch is not building at all.

**Comment by SapuSeven** [comment]
Any reason to go with Java 17?
Android Studio Ladybug is now bundled with JBR21 (https://www.jetbrains.com/idea/whatsnew/2024-2/#page__content-jetbrains-runtime) and I was able to use it to build the project.

**Comment by lm41** [comment]
> Any reason to go with Java 17?

I got it from the android developer site. 
image
https://developer.android.com/build/jdks#compileSdk

**Comment by SapuSeven** [comment]
Managed to get it running now with Java 17.
Thanks!

**Comment by lm41** [comment]
> Managed to get it running now with Java 17. Thanks!

NIce! Thank you. I've got to fixes for Serialization errors. Should I open a PR for them or can I commit directly to the `API` branch?

**Comment by SapuSeven** [comment]
Just open a PR, makes it easier to discuss changes.

**Pull request merged**
