### PR TITLE
Boolean Preference UX

### LINKED ISSUE #72: [Request] Boolean Preference UX
**Describe the solution you'd like**

I have realized that the app mostly uses checkboxes for true/false values where it would make more sense to use toggle switches. I wanted to know what you think about this.

<details>
  <summary><b>Additional context</b></summary>

  An article that explains this in more detail.
 [Checkbox vs Toggle Switch - UX Planet](https://uxplanet.org/checkbox-vs-toggle-switch-7fc6e83f10b8)
</details>

### PR DESCRIPTION
**Pull request by Domi04151309**
Closes #72

### CODE REVIEW

**Comment by Domi04151309** [comment]
@SapuSeven what's the status on this pull request?

**Comment by SapuSeven** [comment]
I just have to verify all themes still work as intended.

**Comment by SapuSeven** [comment]
Ok, while I agree that the green theme accent color makes it hard to distinguish on and off states, but I don't like the idea of just using the primary color. I'd really like some distinct accent color.

**Comment by Domi04151309** [comment]
So new accent colors for the red and green themes are needed. All the other themes do already have a distinct accent color (Untis theme uses the one from the Untis app which is almost like the primary color).

**Comment by SapuSeven** [comment]
Oh, yes, the green and the default theme.
I'm not particularly experienced with designing things like this, so I'd appreciate your opinion.

**Comment by Domi04151309** [comment]
I would suggest `#56BABD` and `#86AEE1`

| `#56BABD` |  `#86AEE1` |
| --- | --- |
|  |  |

**Comment by SapuSeven** [comment]
Looks good!

**Review by SapuSeven — APPROVED** [review]

**Pull request merged**
