### PR TITLE
Adjust dialog corner radius

### PR DESCRIPTION
**Pull request by Domi04151309**
Adjusts the dialogs' corner radius to fit the new dialog styles of newer Android versions.

The attachments dialog for the messages does heavily refuse to inherit the dialog corner radius for some reason.

### CODE REVIEW

**Comment by SapuSeven** [comment]
I looked into the attachments dialog problem and decided to just switch everything to MaterialDialog.
I'm currently working on all the settings dialogs and will merge the PR once this is finished.

**Comment by Domi04151309** [comment]
I'd like to make the MaterialDialog's titles bold when you've finished.

**Comment by SapuSeven** [comment]
Good idea. I decided it's easier to keep the basic preferences as they are, so no further work needed there.

**Comment by Domi04151309** [comment]
The titles should now appear in bold. One minor thing I realized is that the MaterialDialogs dim the background slightly less than the normal AlertDialogs but that shouldn't be an issue.

**Comment by Domi04151309** [comment]
This is ready to merge @SapuSeven

**Comment by SapuSeven** [comment]
Right, looks good.
I also don't see the background dim thing as an issue.

**Pull request merged**
