### PR TITLE
Add Info Indicator

### PR DESCRIPTION
**Pull request by Domi04151309**
This PR adds an info indicator in the form of a white dot in the top-right if there is some additional information provided for the lesson.

### CODE REVIEW

**Comment by SapuSeven** [comment]
I'm not sure if the dot should rather have the same right and top margin, for a more symmetrical look.

**Comment by Domi04151309** [comment]
I'm not sure either but I found that aligning the dot in general is very confusing.

**Comment by Domi04151309** [comment]
This should improve the margins with 8px and 9px. That's as close as I can get.

**Comment by SapuSeven** [comment]
Have you tested this with different item padding settings?

**Comment by Domi04151309** [comment]
Yes, it does use some code that's also used for the other card text so it also works with different item paddings.

**Pull request merged**
