### PR TITLE
Use own banner

### PR DESCRIPTION
**Pull request by Domi04151309**
Removes `com.github.cesarferreira:MaterialComponent.Banner` dependency and uses own banner "implementation"

### CODE REVIEW

**Comment by SapuSeven** [comment]
Actually I am not sure if I should even keep this banner.
I don't think it has much use to be honest...

**Comment by Domi04151309** [comment]
Maybe change the purpose of the banner to encourage bug reporting and improvement suggestions. Also, a call for recommendations to friends could increase user acquisition.

**Comment by SapuSeven** [comment]
That'd be a good idea.
I'll keep this PR open for suggestions.

**Comment by Domi04151309** [comment]
What's the status on this PR?

**Comment by SapuSeven** [comment]
There are still some leftover string resources that break the build

**Comment by Domi04151309** [comment]
Sorry, I didn't see that.

**Comment by Domi04151309** [comment]
Should work now.

**Comment by g3ymer** [comment]
> Removes `com.github.cesarferreira:MaterialComponent.Banner` dependency and uses own banner "implementation"

**Comment by RAPUNZEL49377** [comment]
Finde ich in Ordnung

**Comment by SapuSeven** [comment]
I've been looking into this again recently and I'd like to merge this PR.
Right now it seems that the dialog is for sharing BetterUntis but the link leads to the project README which doesn't really make sense, so I'm open for suggestions on how we could use this banner.

**Comment by Domi04151309** [comment]
Maybe it would make sense to use the Sharesheet to share an URL with people. That could be an URL to the store but maybe also an URL to a general informative page (like the readme or a site hosted with GitHub pages).

**Review by SapuSeven — APPROVED** [review]

**Pull request merged**
