### PR TITLE
Help with 287-material-design-3

### PR DESCRIPTION
**Pull request by lm41**
### TODO

_These items require Untis API data for testing. Currently on hold until the testing API is ready._

- [x] Test QR Code scanning
- [ ] Test yearly profile updates (Data update on school year change) [If all work is done I can do that] 
- [ ] Test all features with actual data [If all work is done I can do that] 
- [x] Implement profile management (Deleting/Editing profiles)
- [x] Implement info center message and homework attachments
- [x] ~Implement absence checking~ [look in #290]
- [x] Implement lesson topic editing
- [x] ~Implement new DataStore preferences - right now, preferences don't work~ [look in #290]
- [x] Implement bookmarks
- [x] Implement holidays
- [x] Implement Untis Messenger integration
- [x] ~Implement date picker for timetable~ [look in #290]
- [x] ~Implement persistent timetable zoom~ [look in #290]
- [ ] Verify auto mute and notification features still work [If all work is done I can do that]

### CODE REVIEW

**Comment by SapuSeven** [comment]
Hey, are you actively working on these features?

PS: For a Testing API, look at the [updated Wiki page](https://github.com/SapuSeven/BetterUntis/wiki/Testing-API).

**Comment by lm41** [comment]
Hey,
i just copied the TODO page from the original PR, because i want to work on features here and there and wanted to avoid duplicate editing. :)
I work in such a way half on the features. every now and then when I have time, although I also have no idea how to implement some of them. (eg date picker)
I already know and use the new testing api :)

**Comment by SapuSeven** [comment]
Ok, in that case I'll keep this PR open for now.
Thanks for your effort :)

**Comment by lm41** [comment]
I have now clearly marked what I will do in the next time. 
And thank you for your work. For me it is now the last year at school. After that, I'll probably have a hard time working with real data. (Unless the testing Api is matured until then).

**Comment by lm41** [comment]
@SapuSeven I'm done for now.

**Pull request merged**
