### PR TITLE
Fixes #275, #334 and other minor improvements

### LINKED ISSUE #275: [Bug Report] Automatic do not disturb does not work on android 12
### Steps to Reproduce

Update your phone to android 12.
give the required permissions

### Expected Result

Automatic do not disturb should work.

### Actual Result

Automatic do not disturb does not work

### Android Version

Android 12

### BetterUntis Version

3.4.8

### Installation Source

F-Droid

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by lm41**
The current method wasn't working if the "github.com" link was registered on another app like github mobile.
https://developer.android.com/training/package-visibility/use-cases#let-non-browser-apps-handle-urls

From: 
```xml
<intent>
	<action android:name="android.intent.action.VIEW" />
	<category android:name="android.intent.category.BROWSABLE" />
	<data android:scheme="https" />
</intent>
```
to
```xml
<intent>
	<action android:name="android.intent.action.VIEW" />
	<category android:name="android.intent.category.BROWSABLE" />
	<data android:scheme="https" android:host="*" />
</intent>
```

### CODE REVIEW

**Comment by lm41** [comment]
Stupid me tested it with 
```xml
<package android:name="com.github.android" />
<package android:name="com.gh4a" />
```
included in the Manifest. I need to find another way to handle the links...

**Comment by SapuSeven** [comment]
I actually tested the link handling on my phone with FastHub and it worked as expected after setting the app as a link handler...

**Comment by lm41** [comment]
Strange. What android version do you have? 
I tracked it down to API 31 and above (Android 12+). In android 11 (API 30) everything works fine, but in API 31 only the "No compatible app found" dialogue opens.

**Comment by lm41** [comment]
I've found this in the logcat and dropped a fix for automute and notifications not working on android 12
```log
2022-12-01 08:45:16.413 20668-20704 NotificationSetup       pid-20668                            E  Notifications couldn't be scheduled
                                                                                                    java.lang.SecurityException: Caller com.sapuseven.untis.debug needs to hold android.permission.SCHEDULE_EXACT_ALARM to set exact alarms.
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:2409)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2392)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2334)
                                                                                                    	at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:359)
                                                                                                    	at android.app.AlarmManager.setImpl(AlarmManager.java:947)
                                                                                                    	at android.app.AlarmManager.setImpl(AlarmManager.java:907)
                                                                                                    	at android.app.AlarmManager.setExact(AlarmManager.java:705)
                                                                                                    	at com.sapuseven.untis.workers.NotificationSetupWorker.scheduleNotification(NotificationSetupWorker.kt:227)
                                                                                                    	at com.sapuseven.untis.workers.NotificationSetupWorker.scheduleNotification$default(NotificationSetupWorker.kt:168)
                                                                                                    	at com.sapuseven.untis.workers.NotificationSetupWorker.scheduleNotifications(NotificationSetupWorker.kt:151)
                                                                                                    	at com.sapuseven.untis.workers.NotificationSetupWorker.doWork(NotificationSetupWorker.kt:74)
                                                                                                    	at androidx.work.CoroutineWorker$startWork$1.invokeSuspend(CoroutineWorker.kt:68)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.alarm.AlarmManagerService$5.set(AlarmManagerService.java:2534)
                                                                                                    	at android.app.IAlarmManager$Stub.onTransact(IAlarmManager.java:194)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1192)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1151)
2022-12-01 08:45:16.420 20668-20701 AutoMuteSetup           pid-20668                            E  Auto mute events couldn't be scheduled
                                                                                                    java.lang.SecurityException: Caller com.sapuseven.untis.debug needs to hold android.permission.SCHEDULE_EXACT_ALARM to set exact alarms.
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:2409)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2392)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2334)
                                                                                                    	at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:359)
                                                                                                    	at android.app.AlarmManager.setImpl(AlarmManager.java:947)
                                                                                                    	at android.app.AlarmManager.setImpl(AlarmManager.java:907)
                                                                                                    	at android.app.AlarmManager.setExact(AlarmManager.java:705)
                                                                                                    	at com.sapuseven.untis.workers.AutoMuteSetupWorker.scheduleAutoMute(AutoMuteSetupWorker.kt:98)
                                                                                                    	at com.sapuseven.untis.workers.AutoMuteSetupWorker.doWork(AutoMuteSetupWorker.kt:47)
                                                                                                    	at androidx.work.CoroutineWorker$startWork$1.invokeSuspend(CoroutineWorker.kt:68)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by lm41** [comment]
What works/was added with this PR:

- [x] Notifications (finally also on android 12)
- [x] Auto Mute (finally also on android 12) fixes #275
- [x] non-browser apps can handle intents now too (finally also on android 12)
- [x] added some translations mentioned in #334

**Review by SapuSeven — APPROVED** [review]
Thanks.
For the alarm permissions: I found the following in [the docs](https://developer.android.com/training/scheduling/alarms#using-schedule-exact-permission):

> Unlike USE_EXACT_ALARM, the SCHEDULE_EXACT_ALARM permission must be granted by the user. Both the user and the system can revoke the SCHEDULE_EXACT_ALARM permission.

So the final fix should instead change notifications to be off by default and when enabling it (or automute) request the permission. I'll do that later.

**Pull request merged**
