### PR TITLE
fix #370 deactivated drawer-opening with swiping

### LINKED ISSUE #370: Drawer is opening though it shouldn't
### Steps to Reproduce

Scroll on the right side of the screen (it takes a few tries until it does what it should not do)

### Expected Result

The drawer should not open when scrolling on the right half of the screen

### Actual Result

The drawer sometimes opens when scrolling on the right half of the screen

### Android Version

Android 13

### BetterUntis Version

4.0.0-beta03-DEBUG

### Installation Source

None

### Additional information

Installation source: GitHub (it was not selectable here)

### PR DESCRIPTION
**Pull request by Lauritz-Tieste**
I disabled the opening of the Navigation Drawer to fix accidental openings

### CODE REVIEW

**Comment by Lauritz-Tieste** [comment]
This is my first pull request to a repository. I hope I did everything correctly.

**Comment by Lauritz-Tieste** [comment]
Could someone review my PR?

**Review by lm41 — CHANGES_REQUESTED** [review]
Only looking at the code I don't think that is the right way to do this. You could add a Setting to let the user decide how to handle this. @SapuSeven did not add `drawerGestures: MutableState<Boolean> = rememberSaveable { mutableStateOf(true) },` (l.1526) without reason.

**Comment by Lauritz-Tieste** [comment]
If the navigation drawer can be opened with a swipe and you scroll through the timetable too quickly, the drawer opens accidentally. As this has been reported as a bug and normal users browse all settings, if there is an option it should be disabled by default. Disabling them would still cause the problem.

**Comment by Lauritz-Tieste** [comment]
I think there is no reason to re-enable swiping.

**Review by lm41 — APPROVED** [review]
Now that you say it makes sense (I had only taken a short time, because vacation). I think this is a better way without abandoning the drawerGestures value. It is always false now so it should work.

**Comment by Lauritz-Tieste** [comment]
I think so too. Thank you

**Comment by lm41** [comment]
@SapuSeven it's ready to merge if you do not have any objections

**Comment by Lauritz-Tieste** [comment]
What's about my pr?

**Comment by SapuSeven** [comment]
Hi, sorry for taking so long.
I haven't got around to testing the changes, as soon as I do I will update this PR.
First look is OK though

**Comment by Lauritz-Tieste** [comment]
The bug annoys me every day 😀 can you test it soon?

**Pull request merged**
