### PR TITLE
Add Pixel Theme

### PR DESCRIPTION
**Pull request by Domi04151309**
This pull request adds a new clean theme inspired by the Pixel devices. Its implementation is a little bit more complicated than the ones of the other themes.

### CODE REVIEW

**Comment by Domi04151309** [comment]
What's the status on this pull request? (And when will the next release be published/which milestones are missing?) @SapuSeven

**Comment by SapuSeven** [comment]
I have yet to test this out, but looks good on first look.
Regarding releases, I don't really have any schedules or milestones but you can expect the next release in about a week.

**Comment by Domi04151309** [comment]
Still no new release. What's missing?

**Comment by SapuSeven** [comment]
Working on it at this moment.
Currently I have problems accessing my Google Play listing, so F-Droid and GitHub will have this update first.

**Comment by Domi04151309** [comment]
I can confirm that Google Play doesn't work right now.

**Comment by SapuSeven** [comment]
Version 3.3.2 is now [published on GitHub](https://github.com/SapuSeven/BetterUntis/releases/tag/v3.3.2) as pre-release until the Play Store becomes accessible again.

**Comment by Domi04151309** [comment]
The Play Store is accessible again.

**Comment by Domi04151309** [comment]
The develop branch wasn't merged before releasing so most changes listed in the changelog aren't available.

**Comment by SapuSeven** [comment]
Not sure how I managed to forget that - thanks for paying attention ;)
Meanwhile I encountered another crash, I'll quickly fix that one first.

**Comment by SapuSeven** [comment]
The new release has been fixed and published.

**Pull request merged**
